#:schema node_modules/wrangler/config-schema.json
name = "twikoo-cloudflare"
main = "src/index.js"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2026-04-23"

[[d1_databases]]
binding = "DB" # available in your Worker on env.DB
database_name = "twikoo"
database_id = "8fd9102c-4e2d-4a39-ab4b-a69a84369c48"

[[r2_buckets]]
binding = "R2"
bucket_name = "twikoo"

[vars]
R2_PUBLIC_URL = "https://twikoo.yezhiyun.com"

[dev]
port = 5000
