#:schema node_modules/wrangler/config-schema.json
name = "twikoo"
main = "src/index.js"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2026-04-23"

[[d1_databases]]
binding = "DB" # available in your Worker on env.DB
database_name = "twikoo"
database_id = "35b51427-ce33-4811-a1f3-a9cc5483e80c"

[[r2_buckets]]
binding = "R2"
bucket_name = "twikoo"

[vars]
R2_PUBLIC_URL = "https://twikoo.yezhiyun.com"

[dev]
port = 5000
